### ISSUE TITLE
Is resilence4j-micronaut artifact dead?

### ISSUE THREAD

**Issue by ddrao** [resilience4j/resilience4j-micronaut-demo#5]
When trying this demo out, it seems resilience4j-micronaut has gone missing from mavencentral. Is that expected? If yes is there a replacement?

**Comment by pollend** [comment]
There is still some work on the micronaut branch to get it to a releasable state. you can't find the artifact because one was never published. 

https://github.com/resilience4j/resilience4j/pull/1179

**Comment by ddrao** [comment]
got it. Any ideas to when this would be released?

**Comment by ddrao** [comment]
Closing this as the artifact in question is a WIP.
